import type { ChatMessage } from "./types";

export const careTeam = [
  { name: "Dr. Mehta", role: "Primary consultant" },
  { name: "Asha", role: "Dialysis coordinator" },
  { name: "Nurse Priya", role: "Ward team" },
];

export const chatMessages: ChatMessage[] = [
  {
    id: "msg-7",
    author: "Ritika Sharma",
    role: "patient",
    source: "sms",
    time: "06:22 PM",
    dayLabel: "Yesterday",
    body: "Also wanted to ask if I should continue the phosphate binder with dinner today.",
  },
  {
    id: "msg-8",
    author: "Dr. Mehta",
    role: "doctor",
    source: "system",
    time: "06:40 PM",
    dayLabel: "Yesterday",
    body: "Yes, continue it with dinner tonight. We’ll review the dose again after the next phosphorus report.",
    meta: "Delivered through SMS",
  },
  {
    id: "msg-1",
    author: "System",
    role: "system",
    source: "system",
    time: "08:10 AM",
    dayLabel: "Today",
    body: "Patient messages from WhatsApp, SMS, and app are merged into one care thread.",
  },
  {
    id: "msg-2",
    author: "Ritika Sharma",
    role: "patient",
    source: "whatsapp",
    time: "08:14 AM",
    dayLabel: "Today",
    body: "Good morning doctor, I felt a little dizzy after yesterday’s dialysis. It improved after breakfast.",
  },
  {
    id: "msg-3",
    author: "Asha",
    role: "team",
    source: "system",
    time: "08:19 AM",
    dayLabel: "Today",
    body: "Noted on behalf of Dr. Mehta. Please share current BP if available.",
    meta: "Sent by dialysis coordinator",
  },
  {
    id: "msg-4",
    author: "Ritika Sharma",
    role: "patient",
    source: "app",
    time: "08:26 AM",
    dayLabel: "Today",
    body: "BP is 108/70. No vomiting. Just mild weakness.",
  },
  {
    id: "msg-5",
    author: "Dr. Mehta",
    role: "doctor",
    source: "system",
    time: "08:41 AM",
    dayLabel: "Today",
    body: "Continue breakfast before morning medicines. If dizziness repeats after the next session, we may review dry weight.",
    meta: "Visible to patient as doctor reply",
  },
  {
    id: "msg-6",
    author: "Team note",
    role: "internal",
    source: "system",
    time: "08:44 AM",
    dayLabel: "Today",
    body: "Flag for post-dialysis review in tomorrow’s round. Check if amlodipine pause is still appropriate.",
  },
];
