import type { TrendParameter, ParameterCategory } from './types';

const DATES = [
  '2026-01-13',
  '2026-02-05',
  '2026-03-15',
  '2026-04-19',
  '2026-05-21',
];

export const TREND_DATES = DATES;
export const TABLE_DATES = DATES.slice(-3).reverse();

export const ALL_CATEGORIES: ParameterCategory[] = [
  'Nephrology',
  'CBC Test',
  'Kidney Function',
];

export const pathologyParameters: TrendParameter[] = [
  {
    id: 'creatinine',
    name: 'Serum Creatinine',
    unit: 'mg/dL',
    referenceRange: { low: 0.6, high: 1.2, label: '0.6–1.2' },
    category: 'Nephrology',
    clinicalLabel: 'Kidney function',
    isKeyParameter: true,
    severityScore: 96,
    dataPoints: [
      { date: DATES[0], value: 7.2 },
      { date: DATES[1], value: 8.1 },
      { date: DATES[2], value: 9.4 },
      { date: DATES[3], value: 8.6 },
      { date: DATES[4], value: 9.1 },
    ],
  },
  {
    id: 'potassium',
    name: 'Potassium',
    unit: 'mEq/L',
    referenceRange: { low: 3.5, high: 5.0, label: '3.5–5.0' },
    category: 'Nephrology',
    clinicalLabel: 'Electrolytes',
    isKeyParameter: true,
    severityScore: 100,
    dataPoints: [
      { date: DATES[0], value: 4.2 },
      { date: DATES[1], value: 5.8 },
      { date: DATES[2], value: 5.1 },
      { date: DATES[3], value: 4.7 },
      { date: DATES[4], value: 5.3 },
    ],
  },
  {
    id: 'phosphorus',
    name: 'Phosphorus',
    unit: 'mg/dL',
    referenceRange: { low: 2.5, high: 4.5, label: '2.5–4.5' },
    category: 'Nephrology',
    clinicalLabel: 'Mineral balance',
    isKeyParameter: true,
    severityScore: 82,
    dataPoints: [
      { date: DATES[0], value: 4.8 },
      { date: DATES[1], value: 5.2 },
      { date: DATES[2], value: 6.1 },
      { date: DATES[3], value: 5.6 },
      { date: DATES[4], value: 5.9 },
    ],
  },
  {
    id: 'blood-urea',
    name: 'Blood Urea',
    unit: 'mg/dL',
    referenceRange: { low: 7, high: 20, label: '7–20' },
    category: 'Kidney Function',
    clinicalLabel: 'Dialysis load',
    isKeyParameter: true,
    severityScore: 78,
    dataPoints: [
      { date: DATES[0], value: 88 },
      { date: DATES[1], value: 94 },
      { date: DATES[2], value: 101 },
      { date: DATES[3], value: 92 },
      { date: DATES[4], value: 98 },
    ],
  },
  {
    id: 'albumin',
    name: 'Albumin',
    unit: 'g/dL',
    referenceRange: { low: 3.5, high: 5.0, label: '3.5–5.0' },
    category: 'Nephrology',
    clinicalLabel: 'Nutrition status',
    isKeyParameter: true,
    severityScore: 88,
    dataPoints: [
      { date: DATES[0], value: 3.1 },
      { date: DATES[1], value: 3.3 },
      { date: DATES[2], value: 3.4 },
      { date: DATES[3], value: 3.3 },
      { date: DATES[4], value: 3.2 },
    ],
  },
  {
    id: 'calcium',
    name: 'Calcium',
    unit: 'mg/dL',
    referenceRange: { low: 8.5, high: 10.5, label: '8.5–10.5' },
    category: 'Kidney Function',
    clinicalLabel: 'Bone-mineral balance',
    isKeyParameter: true,
    severityScore: 84,
    dataPoints: [
      { date: DATES[0], value: 7.8 },
      { date: DATES[1], value: 8.2 },
      { date: DATES[2], value: 7.6 },
      { date: DATES[3], value: 8.0 },
      { date: DATES[4], value: 7.9 },
    ],
  },
  {
    id: 'bicarbonate',
    name: 'Bicarbonate',
    unit: 'mEq/L',
    referenceRange: { low: 22, high: 28, label: '22–28' },
    category: 'Kidney Function',
    clinicalLabel: 'Acid-base balance',
    isKeyParameter: true,
    severityScore: 76,
    dataPoints: [
      { date: DATES[0], value: 19.2 },
      { date: DATES[1], value: 18.6 },
      { date: DATES[2], value: 20.1 },
      { date: DATES[3], value: 21.4 },
      { date: DATES[4], value: 20.8 },
    ],
  },
  {
    id: 'ferritin',
    name: 'Ferritin',
    unit: 'ng/mL',
    referenceRange: { low: 30, high: 400, label: '30–400' },
    category: 'CBC Test',
    clinicalLabel: 'Iron stores',
    isKeyParameter: false,
    severityScore: 48,
    dataPoints: [
      { date: DATES[0], value: 96 },
      { date: DATES[1], value: 102 },
      { date: DATES[2], value: 118 },
      { date: DATES[3], value: 124 },
      { date: DATES[4], value: 116 },
    ],
  },
  {
    id: 'transferrin-sat',
    name: 'Transferrin Saturation',
    unit: '%',
    referenceRange: { low: 20, high: 50, label: '20–50' },
    category: 'CBC Test',
    clinicalLabel: 'Anaemia support',
    isKeyParameter: false,
    severityScore: 58,
    dataPoints: [
      { date: DATES[0], value: 18 },
      { date: DATES[1], value: 17 },
      { date: DATES[2], value: 20 },
      { date: DATES[3], value: 22 },
      { date: DATES[4], value: 19 },
    ],
  },
  {
    id: 'hemoglobin',
    name: 'Hemoglobin',
    unit: 'g/dL',
    referenceRange: { low: 12.0, high: 17.0, label: '12–17' },
    category: 'CBC Test',
    clinicalLabel: 'Blood oxygen carrying',
    isKeyParameter: true,
    severityScore: 90,
    dataPoints: [
      { date: DATES[0], value: 9.2 },
      { date: DATES[1], value: 8.8 },
      { date: DATES[2], value: 9.5 },
      { date: DATES[3], value: 10.1 },
      { date: DATES[4], value: 9.8 },
    ],
  },
  {
    id: 'fbs',
    name: 'Fasting Blood Sugar',
    unit: 'mg/dL',
    referenceRange: { low: 70, high: 100, label: '70–100' },
    category: 'CBC Test',
    clinicalLabel: 'Diabetes monitoring',
    isKeyParameter: true,
    severityScore: 68,
    dataPoints: [
      { date: DATES[0], value: 142 },
      { date: DATES[1], value: 118 },
      { date: DATES[2], value: 96 },
      { date: DATES[3], value: 88 },
      { date: DATES[4], value: 104 },
    ],
  },
  {
    id: 'rbs',
    name: 'Random Blood Sugar',
    unit: 'mg/dL',
    referenceRange: { low: 70, high: 140, label: '70–140' },
    category: 'CBC Test',
    clinicalLabel: 'Diabetes monitoring',
    isKeyParameter: true,
    severityScore: 72,
    dataPoints: [
      { date: DATES[0], value: 198 },
      { date: DATES[1], value: 186 },
      { date: DATES[2], value: 174 },
      { date: DATES[3], value: 162 },
      { date: DATES[4], value: 171 },
    ],
  },
];
