import type { Medication } from "./types";

export const medications: Medication[] = [
  {
    id: "med-epo",
    name: "Erythropoietin alfa",
    brand: "Eprex",
    classCode: "EPO",
    form: "Inj",
    dosage: "4000 IU",
    frequency: "3x / week",
    startDate: "12 Jan 2026",
    endDate: "Ongoing",
    reviewDate: "14 May",
    status: "ongoing",
    indication: "Anaemia support around dialysis schedule",
    prescribedBy: "Dr. Girish",
    specialty: "Nephrology",
    lastUpdated: "Dose confirmed 2d ago",
    tone: "cool"
  },
  {
    id: "med-calcium-acetate",
    name: "Calcium acetate",
    brand: "PhosLo",
    classCode: "PHOS",
    form: "Cap",
    dosage: "667 mg",
    frequency: "With meals",
    startDate: "03 Sep 2025",
    endDate: "Ongoing",
    reviewDate: "18 Apr",
    status: "ongoing",
    indication: "Phosphate binding during dialysis regimen",
    prescribedBy: "Dr. Mehta",
    specialty: "Nephrology",
    lastUpdated: "Dose increased after high phosphorus",
    tone: "gold"
  },
  {
    id: "med-glargine",
    name: "Insulin glargine",
    brand: "Lantus",
    classCode: "INS",
    form: "Inj",
    dosage: "10 IU",
    frequency: "Nightly",
    startDate: "28 Mar 2026",
    endDate: "Ongoing",
    reviewDate: "Tomorrow",
    status: "ongoing",
    indication: "Fasting sugar control during dialysis follow-up",
    prescribedBy: "Dr. Patel",
    specialty: "Endocrinology",
    lastUpdated: "Reduced from 14 IU",
    tone: "mint"
  },
  {
    id: "med-bicarbonate",
    name: "Sodium bicarbonate",
    brand: "Sodamint",
    classCode: "ALK",
    form: "Tab",
    dosage: "650 mg",
    frequency: "Twice / day",
    startDate: "20 Aug 2025",
    endDate: "Ongoing",
    reviewDate: "12 May",
    status: "ongoing",
    indication: "Metabolic acidosis support between dialysis reviews",
    prescribedBy: "Dr. Mehta",
    specialty: "Nephrology",
    lastUpdated: "Continue current dose",
    tone: "cool"
  },
  {
    id: "med-torsemide",
    name: "Torsemide",
    brand: "Dytor",
    classCode: "DIU",
    form: "Tab",
    dosage: "20 mg",
    frequency: "Morning",
    startDate: "20 Aug 2025",
    endDate: "Ongoing",
    reviewDate: "14 May",
    status: "ongoing",
    indication: "Residual fluid overload control on non-dialysis days",
    prescribedBy: "Dr. Mehta",
    specialty: "Nephrology",
    lastUpdated: "Stable across last two reviews",
    tone: "ink"
  },
  {
    id: "med-amlodipine",
    name: "Amlodipine",
    brand: "Norvasc",
    classCode: "CARD",
    form: "Tab",
    dosage: "5 mg",
    frequency: "Once / day",
    startDate: "03 Jan 2026",
    endDate: "15 Aug 2026",
    reviewDate: "On hold",
    status: "paused",
    indication: "Paused after low-pressure readings during MHD week — restart pending home BP log review",
    prescribedBy: "Dr. Smith",
    specialty: "Cardiology",
    lastUpdated: "Hold confirmed 8 Apr 2026",
    tone: "gold"
  },
  {
    id: "med-metformin",
    name: "Metformin",
    brand: "Glucophage",
    classCode: "DIA",
    form: "Tab",
    dosage: "500 mg",
    frequency: "Twice / day",
    startDate: "20 Aug 2025",
    endDate: "24 Sep 2025",
    reviewDate: "Completed",
    status: "completed",
    indication: "Stopped at dialysis initiation — contraindicated in dialysis-dependent CKD",
    prescribedBy: "Dr. Patel",
    specialty: "Endocrinology",
    lastUpdated: "Stopped at dialysis initiation Sep 2025",
    tone: "ink"
  }
];
