import type { DialysisWorkspace } from "./types";

export const dialysisWorkspaces: DialysisWorkspace[] = [
  {
    patientId: "pt-001",
    shiftLabel: "Today · 2nd shift · 02:00 PM",
    station: "Station 04",
    chair: "Chair B2",
    unit: "Hemodialysis unit",
    nephrologist: "Dr. Mehta",
    access: "Right IJ permcath",
    serology: "HBsAg non-reactive · HCV non-reactive",
    dryWeight: "64.0 kg",
    preWeight: "66.2 kg",
    targetUf: "2.2 L",
    anticoagulation: "Heparin bolus 1,500 U",
    treatmentDuration: "4 hr",
    dialyzer: "F160",
    dialysate: "K2 · Ca 2.5 · HCO3 35",
    bloodFlow: "250 mL/min",
    machineNumber: "M-07",
    startedBy: "Asha RN",
    assistedBy: "Ravi technician",
    readinessSummary: "Review pre-HD weight, UF goal, and elevated pre-session blood pressure before start.",
    readinessItems: [
      {
        id: "access",
        label: "Vascular access",
        value: "Permcath patent",
        supporting: "No redness or discharge reported",
        status: "ready",
      },
      {
        id: "serology",
        label: "Viral serology",
        value: "Non-reactive",
        supporting: "Cleared for routine bay placement",
        status: "ready",
      },
      {
        id: "weight",
        label: "Dry vs pre-HD weight",
        value: "64.0 kg → 66.2 kg",
        supporting: "+2.2 kg interdialytic gain matches UF target",
        status: "review",
      },
      {
        id: "heparin",
        label: "Anticoagulation",
        value: "Bolus 1,500 U",
        supporting: "Continue as per prior tolerated session",
        status: "ready",
      },
    ],
    preVitals: [
      { label: "Blood pressure", value: "168/96", supporting: "Pre HD", tone: "danger" },
      { label: "Pulse", value: "88", supporting: "Regular", tone: "neutral" },
      { label: "Temperature", value: "98.4 F", supporting: "Afebrile", tone: "neutral" },
      { label: "Target UF", value: "2.2 L", supporting: "Based on dry weight", tone: "warning" },
    ],
    liveVitals: [
      { label: "Elapsed", value: "01:16", supporting: "Started 02:08 PM", tone: "neutral" },
      { label: "Blood pressure", value: "154/88", supporting: "Stable after start", tone: "warning" },
      { label: "UF removed", value: "0.9 L", supporting: "Of 2.2 L goal", tone: "neutral" },
      { label: "Blood flow", value: "250", supporting: "mL/min", tone: "neutral" },
    ],
    prescriptionFields: [
      { label: "Treatment time", value: "4 hr", supporting: "Routine maintenance HD" },
      { label: "Dialyzer", value: "F160", supporting: "Reuse #3" },
      { label: "Dialysate", value: "K2 · Ca 2.5", supporting: "Bicarb 35" },
      { label: "Blood flow", value: "250 mL/min", supporting: "Dialysate flow 500 mL/min" },
      { label: "UF goal", value: "2.2 L", supporting: "Return to dry weight 64.0 kg" },
      { label: "Heparin", value: "1,500 U bolus", supporting: "No infusion planned" },
    ],
    timeline: [
      {
        id: "review",
        time: "01:55 PM",
        title: "Pre-start review completed",
        detail: "Orders, access, weight gap, and serology confirmed at chairside.",
        status: "done",
      },
      {
        id: "start",
        time: "02:08 PM",
        title: "Dialysis initiated",
        detail: "Machine primed, access connected, and blood flow reached prescribed rate.",
        status: "current",
      },
      {
        id: "monitor",
        time: "02:45 PM",
        title: "Thirty-minute check due",
        detail: "Recheck BP, access flow, cramps, and UF tolerance.",
        status: "upcoming",
      },
    ],
    recentSessions: [
      {
        id: "session-1",
        date: "15 May 2026",
        shift: "2nd shift",
        ufRemoved: "2.0 L",
        preBp: "162/92",
        postBp: "146/84",
        outcome: "Tolerated well",
      },
      {
        id: "session-2",
        date: "13 May 2026",
        shift: "2nd shift",
        ufRemoved: "2.4 L",
        preBp: "170/94",
        postBp: "150/86",
        outcome: "Mild cramps in last hour",
      },
      {
        id: "session-3",
        date: "11 May 2026",
        shift: "2nd shift",
        ufRemoved: "1.8 L",
        preBp: "158/90",
        postBp: "142/82",
        outcome: "Stable session",
      },
    ],
    notes: [
      "Review intradialytic cramps if UF exceeds 2.2 L.",
      "Keep access dressing dry after session and reassess exit site tomorrow.",
    ],
  },
];
