import type { PrescriptionRecord } from "./types";

export const prescriptions: PrescriptionRecord[] = [
  {
    id: "rx-12-may-2026",
    title: "Nephrology follow-up Rx",
    createdAt: "12 May 2026",
    groupLabel: "This week",
    department: "Nephrology",
    doctor: "Dr. Mehta",
    status: "draft",
    summary: "Dry-weight review, appetite decline, and potassium follow-up after the last dialysis week.",
    complaints: "Fatigue, reduced appetite, intermittent cramps after dialysis, poor sleep for 3 nights.",
    diagnosis: "CKD on maintenance hemodialysis with hyperkalemia risk and intradialytic cramps.",
    vitals: [
      { label: "BP", value: "142/88" },
      { label: "Pulse", value: "84 bpm" },
      { label: "Weight", value: "68.2 kg" },
    ],
    medications: [
      {
        id: "rx-med-1",
        name: "Calcium acetate",
        form: "Cap",
        strength: "667 mg",
        frequency: "1-1-1",
        duration: "14 days",
        timing: "After meals",
        notes: "Continue phosphate binder with every major meal.",
      },
      {
        id: "rx-med-2",
        name: "Torsemide",
        form: "Tab",
        strength: "20 mg",
        frequency: "1-0-0",
        duration: "14 days",
        timing: "Morning",
        notes: "Continue on non-dialysis days.",
      },
    ],
    investigations: [
      {
        id: "rx-investigation-1",
        name: "Serum potassium",
        category: "Electrolytes",
        instructions: "Repeat before next dialysis session.",
      },
      {
        id: "rx-investigation-2",
        name: "CBC",
        category: "Blood tests",
        instructions: "Check Hb trend during follow-up review.",
      },
    ],
    advice: "Restrict high-potassium foods, maintain dialysis attendance, and bring home BP log to next visit.",
    followUp: "Review after 7 days or earlier if weakness, palpitations, or breathlessness worsen.",
    dictationPrompt: "Patient with CKD on MHD. Review appetite, cramps, dry weight, potassium trend, and continue renal regimen.",
  },
  {
    id: "rx-08-apr-2026",
    title: "OPD consultation Rx",
    createdAt: "08 Apr 2026",
    groupLabel: "This month",
    department: "Nephrology",
    doctor: "Dr. Mehta",
    status: "signed",
    summary: "Hypertension guidance tightened and phosphate binder reviewed after latest pathology trends.",
    complaints: "Tiredness, appetite variation, morning BP fluctuations.",
    diagnosis: "CKD with blood pressure variability and phosphorus elevation.",
    vitals: [
      { label: "BP", value: "138/86" },
      { label: "Pulse", value: "82 bpm" },
      { label: "Weight", value: "67.8 kg" },
    ],
    medications: [
      {
        id: "rx-med-3",
        name: "Amlodipine",
        form: "Tab",
        strength: "5 mg",
        frequency: "1-0-0",
        duration: "10 days",
        timing: "Morning",
        notes: "Restart low dose after reviewing home BP trend.",
      },
      {
        id: "rx-med-4",
        name: "Calcium acetate",
        form: "Cap",
        strength: "667 mg",
        frequency: "1-1-1",
        duration: "10 days",
        timing: "After meals",
        notes: "Continue without interruption.",
      },
    ],
    investigations: [
      {
        id: "rx-investigation-3",
        name: "KFT panel",
        category: "Renal panel",
        instructions: "Repeat before next OPD review.",
      },
    ],
    advice: "Continue salt restriction and report dizziness if morning BP drops again.",
    followUp: "Review in 10 days with home BP readings.",
    dictationPrompt: "Follow-up nephrology prescription for BP review and phosphate management.",
  },
  {
    id: "rx-18-mar-2026",
    title: "Dialysis review Rx",
    createdAt: "18 Mar 2026",
    groupLabel: "Earlier",
    department: "Dialysis unit",
    doctor: "Dr. Girish",
    status: "signed",
    summary: "Supportive regimen updated after dialysis tolerance review and cramp monitoring.",
    complaints: "Post-session cramps and fatigue.",
    diagnosis: "Post-dialysis cramp tendency with anemia support ongoing.",
    vitals: [
      { label: "BP", value: "136/84" },
      { label: "Pulse", value: "80 bpm" },
      { label: "Weight", value: "68.5 kg" },
    ],
    medications: [
      {
        id: "rx-med-5",
        name: "Erythropoietin alfa",
        form: "Inj",
        strength: "4000 IU",
        frequency: "3x/week",
        duration: "2 weeks",
        timing: "Dialysis days",
        notes: "Continue as per dialysis schedule.",
      },
    ],
    investigations: [],
    advice: "Hydration between sessions and report worsening cramps to dialysis unit.",
    followUp: "Review next dialysis week.",
    dictationPrompt: "Dialysis review prescription with anemia support and cramp management advice.",
  },
];
